# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medeina', '0003_create_initial_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecategory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
