# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medeina', '0006_create_initial_issues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuecategory',
            options={'verbose_name_plural': 'Issue categories'},
        ),
    ]
