# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medeina', '0007_auto_20180405_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
